steps:
  - name: gcr.io/cloud-builders/docker
    secretEnv: ["GOOGLE_CLIENT_SECRET", "STRIPE_SECRET_KEY"]
    args:
      - build
      - '--no-cache'
      - '-t'
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - "--build-arg"
      - "GOOGLE_CLIENT_ID=819221826816-lclugm0rj3udse60vjmelf4jophnu7mk.apps.googleusercontent.com"
      - "--build-arg"
      - "GOOGLE_CLIENT_SECRET=$$GOOGLE_CLIENT_SECRET"
      - "--build-arg"
      - "STRIPE_SECRET_KEY=$$STRIPE_SECRET_KEY"
      - "--build-arg"
      - "STRIPE_PRICE_ID=price_1SxAY1GsEWhVvfBlrj6Nc6gM"
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: projects/funky-485504/locations/us-central1/workerPools/private-build-pool
substitutions:
  _SERVICE_NAME: funky-landing
  _DEPLOY_REGION: us-central1
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _AR_PROJECT_ID: funky-485504
  _PLATFORM: managed
  _TRIGGER_ID: 8013d585-18e1-4fb2-977d-64ddda8ceed2
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - funky-landing
availableSecrets:
  secretManager:
    - versionName: "projects/$PROJECT_ID/secrets/google_client_secret/versions/latest"
      env: "GOOGLE_CLIENT_SECRET"
    - versionName: "projects/$PROJECT_ID/secrets/stripe_secret_key/versions/latest"
      env: "STRIPE_SECRET_KEY"